export const mockOrders: Order[] = [
  {
    orderId: 101,
    customerId: 341323123,
    campus: 1,
    shopId: "King Burger",
    totalOrderAmount: 2500.0,
    totalDiscount: 100.0,
    refundStatus: "NOT_REFUNDED",
    totalInvoiceAmount: 2400.0,
    creationTime: "12/01/2025 [12:14pm]",
    additionalPaymentCharges: 0.0,
    totalOrderAmountIncludingPaymentCharges: 2500.0,
    totalInvoiceAmountIncludingPaymentCharges: 2400.0,
    paymentMethod: "UPI",
    cancelReason: null,
    state: "CONFIRMED",
    customerName: "Rahul Sharma",
    customerMobileNumber: "9876543210",
    pickupAddress: {
      addressLine1: "#6, 4th cross, Bjp rd",
      addressLine2: "Indiranager",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560048",
      latitude: "12.9352",
      longitude: "77.6245",
    },
    customerDeliveryAddress: {
      name: "Rahul Sharma",
      addressLine1: "Apt 12, MG Road",
      addressLine2: "Koramangala",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560095",
      latitude: "12.9352",
      longitude: "77.6245",
    },
    deliveryFees: 50.0,
    totalItemCount: 3,
    amountExcludingDeliveryFee: 2450.0,
    fulfillmentOption: "DELIVERY",
    selfDeliveryMode: null,
    deliveryAgentName: "Arun Kumar",
    deliveryAgentMobileNumber: "9876543222",
    deliveryPartnerName: "QuickDelivery",
    trackingId: "TRK12345",
    deliveryTime: Date.now() + 3600 * 1000,
    trackingUrl: "https://trackingurl.com/TRK12345",
    platform: "QUICKVERSE",
    smartBizOffers: ["10% OFF"],
    orderDescription: "Groceries",
    orderLink: "https://orderlink.com/101",
    stateLabel: "Confirmed",
  },
  {
    orderId: 102,
    customerId: 341323124,
    campus: 2,
    shopId: "Hotz Pizza",
    totalOrderAmount: 1800.0,
    totalDiscount: 0.0,
    refundStatus: "NOT_REFUNDED",
    totalInvoiceAmount: 1800.0,
    creationTime: "12/01/2024 [02:36pm]",
    additionalPaymentCharges: 0.0,
    totalOrderAmountIncludingPaymentCharges: 1800.0,
    totalInvoiceAmountIncludingPaymentCharges: 1800.0,
    paymentMethod: "COD",
    cancelReason: null,
    state: "PENDING",
    customerName: "Neha Gupta",
    customerMobileNumber: "9867543211",
    pickupAddress: {
      addressLine1: "#256, 2nd block, 8th cross",
      addressLine2: "Kormangla",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560048",
      latitude: "12.9352",
      longitude: "77.6245",
    },
    customerDeliveryAddress: {
      name: "Neha Gupta",
      addressLine1: "Flat 202, Whitefield",
      addressLine2: "Marathahalli",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560037",
      latitude: "12.9716",
      longitude: "77.6413",
    },
    deliveryFees: 30.0,
    totalItemCount: 1,
    amountExcludingDeliveryFee: 1770.0,
    fulfillmentOption: "DELIVERY",
    selfDeliveryMode: null,
    deliveryAgentName: null,
    deliveryAgentMobileNumber: null,
    deliveryPartnerName: null,
    trackingId: null,
    deliveryTime: 0,
    trackingUrl: null,
    platform: "QUICKVERSE",
    smartBizOffers: [],
    orderDescription: "Electronics",
    orderLink: "https://orderlink.com/102",
    stateLabel: "Pending",
  },
  {
    orderId: 103,
    customerId: 341323125,
    campus: 3,
    shopId: "Punjabi Dhaba",
    totalOrderAmount: 999.0,
    totalDiscount: 50.0,
    refundStatus: "REFUNDED",
    totalInvoiceAmount: 949.0,
    creationTime: "12/01/2024 [01:12pm]",
    additionalPaymentCharges: 0.0,
    totalOrderAmountIncludingPaymentCharges: 999.0,
    totalInvoiceAmountIncludingPaymentCharges: 949.0,
    paymentMethod: "CREDIT_CARD",
    cancelReason: null,
    state: "CANCELLED",
    customerName: "Amit Verma",
    customerMobileNumber: "9876123456",
    pickupAddress: {
      addressLine1: "HP petrolpump, ramnagar",
      addressLine2: "Domlur",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560048",
      latitude: "12.9352",
      longitude: "77.6245",
    },
    customerDeliveryAddress: {
      name: "Amit Verma",
      addressLine1: "House 45, JP Nagar",
      addressLine2: "Phase 7",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560078",
      latitude: "12.9100",
      longitude: "77.6000",
    },
    deliveryFees: 20.0,
    totalItemCount: 2,
    amountExcludingDeliveryFee: 929.0,
    fulfillmentOption: "PICKUP",
    selfDeliveryMode: "STORE_PICKUP",
    deliveryAgentName: null,
    deliveryAgentMobileNumber: null,
    deliveryPartnerName: null,
    trackingId: null,
    deliveryTime: 0,
    trackingUrl: null,
    platform: "QUICKVERSE",
    smartBizOffers: ["5% Cashback"],
    orderDescription: "Clothing",
    orderLink: "https://orderlink.com/103",
    stateLabel: "Cancelled",
  },
];

// Generate 7 more mock orders dynamically
for (let i = 104; i <= 110; i++) {
  mockOrders.push({
    orderId: i,
    customerId: 341323120 + i,
    campus: 3 + (i - 103),
    shopId: ["Hotz Pizza", "King Burger", "Punjabi Dhaba"][
      Math.floor(Math.random() * 3)
    ],
    totalOrderAmount: Math.floor(Math.random() * 5000) + 500,
    totalDiscount: Math.floor(Math.random() * 200),
    refundStatus: "NOT_REFUNDED",
    totalInvoiceAmount: Math.floor(Math.random() * 5000) + 500,
    creationTime: "12/01/2024 [10:46am]",
    additionalPaymentCharges: 0.0,
    totalOrderAmountIncludingPaymentCharges:
      Math.floor(Math.random() * 5000) + 500,
    totalInvoiceAmountIncludingPaymentCharges:
      Math.floor(Math.random() * 5000) + 500,
    paymentMethod: ["COD", "UPI", "CREDIT_CARD"][Math.floor(Math.random() * 3)],
    cancelReason: null,
    state: ["PENDING", "CONFIRMED", "DELIVERED", "CANCELLED"][
      Math.floor(Math.random() * 4)
    ],
    customerName: `Customer ${i}`,
    customerMobileNumber: `98765${Math.floor(Math.random() * 100000)}`,
    pickupAddress: {
      addressLine1: "#6, 4th cross, Bjp rd",
      addressLine2: "Indiranager",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "560048",
      latitude: "12.9352",
      longitude: "77.6245",
    },
    customerDeliveryAddress: {
      name: `Customer ${i}`,
      addressLine1: `Flat ${i}, Some Road`,
      addressLine2: "Some Area",
      addressLine3: "",
      city: "BENGALURU",
      state: "KARNATAKA",
      pincode: "5600" + Math.floor(Math.random() * 100),
      latitude: (12.9 + Math.random() * 0.1).toFixed(5),
      longitude: (77.5 + Math.random() * 0.1).toFixed(5),
    },
    deliveryFees: Math.floor(Math.random() * 100),
    totalItemCount: Math.floor(Math.random() * 10) + 1,
    amountExcludingDeliveryFee: Math.floor(Math.random() * 5000) + 500,
    fulfillmentOption: "DELIVERY",
    selfDeliveryMode: null,
    deliveryAgentName: ["Arun", "Ramesh", "Suresh", null][
      Math.floor(Math.random() * 4)
    ],
    deliveryAgentMobileNumber:
      Math.random() > 0.5 ? `98765${Math.floor(Math.random() * 100000)}` : null,
    deliveryPartnerName: Math.random() > 0.5 ? "QuickDelivery" : null,
    trackingId:
      Math.random() > 0.5 ? `TRK${Math.floor(Math.random() * 10000)}` : null,
    deliveryTime: Date.now() + Math.floor(Math.random() * 50000),
    trackingUrl: null,
    platform: "QUICKVERSE",
    smartBizOffers: [],
    orderDescription: "Random items",
    orderLink: `https://orderlink.com/${i}`,
    stateLabel: "Label",
  });
}
